# Generated by Django 2.2.3 on 2019-10-30 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_detail',
            fields=[
                ('Cab_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cab_number', models.CharField(max_length=30)),
                ('Car_model', models.CharField(max_length=30)),
                ('Car_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('Customer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=200)),
                ('C_Phone_no', models.CharField(max_length=30)),
                ('C_Mail_Id', models.EmailField(max_length=254)),
                ('H_address', models.CharField(max_length=1000)),
                ('Password', models.CharField(max_length=30)),
                ('C_Gender', models.CharField(max_length=30)),
                ('C_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver_detail',
            fields=[
                ('Driver_Id', models.AutoField(primary_key=True, serialize=False)),
                ('D_Name', models.CharField(max_length=300)),
                ('D_Phone_no', models.CharField(max_length=30)),
                ('D_Mail_Id', models.EmailField(max_length=254)),
                ('Experience', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Rides_completed', models.IntegerField()),
                ('D_DOB', models.DateField()),
                ('D_Gender', models.CharField(max_length=30)),
                ('License_no', models.CharField(max_length=30)),
                ('Region', models.CharField(max_length=500)),
                ('Active', models.IntegerField()),
                ('Cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Cab_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('Ride_no', models.AutoField(primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=300)),
                ('Destination', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Booking_time', models.TimeField()),
                ('Date_book', models.DateField()),
                ('Reviewed', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Customer_detail')),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Driver_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_no', models.AutoField(primary_key=True, serialize=False)),
                ('Stars', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Customer_detail')),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Driver_detail')),
                ('Ride_no', models.ForeignKey(db_column='Ride_no', on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Ride')),
            ],
        ),
        migrations.CreateModel(
            name='Cab_location',
            fields=[
                ('Serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=5000)),
                ('Zone', models.CharField(max_length=50)),
                ('On_trip_status', models.CharField(max_length=100)),
                ('Cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoCabs.Cab_detail')),
            ],
        ),
    ]
